server:
  port: 10001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka,http://localhost:10002/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: sc03eureka_server